services:
  app:
    build:
      context: .
      target: build
    command: npm run dev
    env_file: .env
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.cache
      - /app/build
      - /app/public/build
    ports:
      - 3000:3000
    depends_on:
      - database
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: form-maker
      POSTGRES_DB: form-maker
      POSTGRES_PASSWORD: form-maker-pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
    driver: local